- hosts: web
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - nginx

    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
